name = "gayness-scale-api"
main = "src/index.ts"
compatibility_date = "2024-02-22"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTH0_DOMAIN = "dev-7y1grk6neur7cepa.us.auth0.com"
AUTH0_AUDIENCE = "https://gayness-scale-backend/"

[[d1_databases]]
binding = "DB"
database_name = "gayness-scale-db"
database_id = "854ea3b8-5140-4540-977a-9cc504e73675"

[dev]
port = 8787
local_protocol = "http"
ip = "127.0.0.1" 