name = "gayness-scale-api"
main = "src/index.ts"
compatibility_date = "2024-02-22"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTH0_DOMAIN = "dev-7y1grk6neur7cepa.us.auth0.com"
AUTH0_AUDIENCE = "https://gayness-scale-api.com"

[[d1_databases]]
binding = "DB"
database_name = "gayness-scale-db"
database_id = "6ab634ac-23cc-42f7-881d-4a174914c10e"

[dev]
port = 8787
local_protocol = "http"
ip = "127.0.0.1" 